### ISSUE TITLE
Wrong DEC values in image extensions 1 and 2

### ISSUE THREAD

**Issue by riccardo-seppi** [domeckert/voronoi#1]
The DEC values in the image extensions 1 and 2 span huge values, almost -90 to 90.
It seems to be due to the CDELT2 parameter in the header, set to 2.5.
Should it be &tps instead of &pixsize in these lines?
https://github.com/domeckert/voronoi/blob/00ec3e18557e42890958de4b3129432ca7da7fb6/voronoi.C#L661
https://github.com/domeckert/voronoi/blob/00ec3e18557e42890958de4b3129432ca7da7fb6/voronoi.C#L683

**Comment by domeckert** [comment]
Correct, thanks @riccardo-seppi . I'll fix this in a second.

**Comment by domeckert** [comment]
Fixed. Closing issue
